import { createHash } from 'node:crypto';

function stableCopy(value) {
  if (Array.isArray(value)) return value.map(stableCopy);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, stableCopy(value[key])]),
    );
  }
  return value;
}

function signature(seed, value) {
  return createHash('sha256')
    .update(seed)
    .update(JSON.stringify(stableCopy(value)))
    .digest('hex')
    .slice(0, 12);
}

function makeEvidence(task, count, fixedTime, runSignature) {
  return Array.from({ length: count }, (_, index) => ({
    evidence_id: `mock-evidence-${index + 1}-${runSignature}`,
    claim: `Mock claim ${index + 1} for task ${task.task_id}`,
    source: {
      uri: `mock://source/${index + 1}/${runSignature}`,
      source_type: 'mock',
      title: `Deterministic mock source ${index + 1}`,
    },
    retrieved_at: fixedTime,
    confidence: 1,
    verification_status: count > 1 ? 'corroborated' : 'single-source',
    adopted: true,
    reason: 'Generated by the deterministic mock to exercise the evidence pipeline.',
    conflict_set: [],
  }));
}

function formatMockOutput(task, payload) {
  const kind = task.output_contract?.format ?? 'json';
  if (kind === 'json' || kind === 'change-proposal') {
    return { kind, content: payload };
  }
  const serialized = JSON.stringify(payload, null, 2);
  if (kind === 'markdown') {
    return { kind, content: `## Deterministic mock output\n\n\`\`\`json\n${serialized}\n\`\`\`` };
  }
  return { kind: 'text', content: serialized };
}

/**
 * Create a deterministic, in-memory adapter.
 *
 * It does not import filesystem or network modules and never applies changes.
 * Equal seed + equal request produces equal adapter responses.
 */
export function createMockAdapter(options = {}) {
  const seed = options.seed ?? 'agent-foundry-vault-mock-v1';
  const fixedTime = options.fixedTime ?? '2026-01-01T00:00:00.000Z';
  if (Number.isNaN(new Date(fixedTime).getTime())) {
    throw new TypeError('fixedTime must be a valid date-time string');
  }

  return Object.freeze({
    name: 'deterministic-mock',
    version: '1.0.0',
    isMock: true,
    appliesChanges: false,
    writesToDisk: false,

    async execute(request) {
      const { role, task, route, context } = request ?? {};
      if (!['router', 'worker', 'writer', 'reviewer'].includes(role)) {
        throw new TypeError(`mock adapter does not support role: ${String(role)}`);
      }
      if (!task || !route || !context) {
        throw new TypeError('mock adapter requires role, task, route, and context');
      }

      const runSignature = signature(seed, {
        role,
        task,
        route,
        previousRoles: context.nodeResults?.map((item) => item.role) ?? [],
        evidenceCount: context.evidenceLedger?.items?.length ?? 0,
      });

      if (role === 'router') {
        return {
          kind: 'route-ack',
          output: {
            kind: 'json',
            content: {
              selected_mode: route.mode,
              signature: runSignature,
            },
          },
        };
      }

      if (role === 'worker') {
        if (route.mode === 'research') {
          const minSources = Math.max(1, task.evidence_policy?.min_sources ?? 1);
          const evidence = makeEvidence(task, minSources, fixedTime, runSignature);
          return {
            kind: 'research-result',
            output: formatMockOutput(task, {
                summary: `Deterministic mock research result for ${task.task_id}`,
                evidence_ids: evidence.map((item) => item.evidence_id),
                signature: runSignature,
            }),
            evidence,
          };
        }

        if (route.mode === 'governed-write') {
          return {
            kind: 'write-preflight',
            output: {
              kind: 'json',
              content: {
                prepared: true,
                targets: [...(task.write_gate?.target_paths ?? [])],
                signature: runSignature,
              },
            },
          };
        }

        return {
          kind: 'direct-result',
          output: formatMockOutput(task, {
              summary: `Deterministic mock direct result for ${task.task_id}`,
              input_keys: Object.keys(task.input).sort(),
              signature: runSignature,
          }),
        };
      }

      if (role === 'writer') {
        return {
          kind: 'change-proposal',
          proposal: {
            proposal_id: `proposal-${runSignature}`,
            targets: [...(task.write_gate?.target_paths ?? [])],
            objective: task.objective,
            approval_state: task.write_gate?.approval_state ?? 'missing',
            changes: [
              {
                operation: 'propose-only',
                description: `Mock change proposal ${runSignature}; no filesystem mutation performed.`,
              },
            ],
            verification: task.acceptance_criteria.map((criterion) => `Verify: ${criterion}`),
            rollback: 'No rollback is required because the mock adapter never applies the proposal.',
            applied: false,
          },
        };
      }

      const evidenceCount = context.evidenceLedger?.items?.length ?? 0;
      if (route.mode === 'research') {
        const required = task.evidence_policy?.min_sources ?? 0;
        const passed = evidenceCount >= required;
        return {
          kind: 'review-verdict',
          verdict: {
            status: passed ? 'passed' : 'failed',
            notes: [
              passed
                ? `Mock evidence gate passed with ${evidenceCount} item(s).`
                : `Mock evidence gate failed: expected ${required}, received ${evidenceCount}.`,
            ],
          },
        };
      }

      if (route.mode === 'governed-write') {
        return {
          kind: 'review-verdict',
          verdict: {
            status: 'needs-human',
            notes: [
              'Mock reviewed the proposal shape; a human approval and a real write adapter are still required.',
            ],
          },
        };
      }

      return {
        kind: 'review-verdict',
        verdict: {
          status: 'passed',
          notes: ['Mock review passed.'],
        },
      };
    },
  });
}
